/**
 * RFC 7807 Problem Details for HTTP APIs
 * https://www.rfc-editor.org/rfc/rfc7807
 * 
 * Standardized error response format for AssetSim Pro API
 * Implements ADR-018: Standardized Error Handling
 */
export interface ProblemDetails {
  /**
   * A URI reference that identifies the problem type
   * Should dereference to human-readable documentation
   * Example: "https://assetsim.com/errors/insufficient-funds"
   */
  type: string;

  /**
   * A short, human-readable summary of the problem type
   * Should not change between occurrences, except for localization
   * Example: "Insufficient Funds"
   */
  title: string;

  /**
   * The HTTP status code generated by the origin server
   * Example: 400
   */
  status: number;

  /**
   * A human-readable explanation specific to this occurrence of the problem
   * Example: "Order value $50,000 exceeds buying power $10,000."
   */
  detail: string;

  /**
   * A URI reference that identifies the specific occurrence of the problem
   * Example: "/orders/123"
   */
  instance?: string;

  /**
   * Additional error details (e.g., validation errors)
   */
  errors?: unknown[];
}

/**
 * Common error types used across AssetSim Pro
 */
export const ErrorTypes = {
  VALIDATION_ERROR: 'https://assetsim.com/errors/validation-error',
  UNAUTHORIZED: 'https://assetsim.com/errors/unauthorized',
  FORBIDDEN: 'https://assetsim.com/errors/forbidden',
  NOT_FOUND: 'https://assetsim.com/errors/not-found',
  INSUFFICIENT_FUNDS: 'https://assetsim.com/errors/insufficient-funds',
  SERVICE_UNAVAILABLE: 'https://assetsim.com/errors/service-unavailable',
  INTERNAL_ERROR: 'https://assetsim.com/errors/internal-error',
} as const;

export function financeModels(): string {
  return 'finance-models';
}
